name: Testes Web no Robot Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: robotframework/robotframework:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -yq \
        curl \
        unzip \
        wget \
        xvfb \
        && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
        && apt-get install -yq nodejs

    - name: Start Xvfb
      run: Xvfb -ac :99 &

    - name: Run tests on Chrome
      run: |
        robot --variable BROWSER:chrome tests/

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: output.xml

    - name: Run tests on Edge
      run: |
        robot --variable BROWSER:edge tests/

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: output.xml

    - name: Send Notification on Failure
      if: always()
      uses: actions/slack@v3.1.0
      with:
        status: ${{ job.status }}
        fields: title, commit, author, status, conclusion, job, logs
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: my-channel
