name: Web Tests

on: [push]

jobs:
  test:
    name: Web Tests
    runs-on: ubuntu-latest
    container:
      image: robotframework/robotframework:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && \
        apt-get install -y curl unzip wget && \
        curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
        apt-get install -y nodejs && \
        npm install -g chromedriver
    - name: Run tests
      run: |
        chromedriver &
        robot --outputdir test_results --variable BROWSER:Chrome tests/
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: test_results/
