name: Testes Web no Chrome com Robot Framework

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Testar no Chrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          npm install
          npm install robotframework-webdriverlibrary
          npm install webdriver-manager@latest
          npm install chromedriver

      - name: Run Tests
        run: |
          webdriver-manager update --chrome --versions.chrome 98.0.4758.102
          robot --outputdir ./TestResults ./E2E
