name: Testes Web no Google Chrome no modo headless
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chrome-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
      options: --user=root
    steps:
      - uses: actions/checkout@v2
      
      # Instala as dependências do ChromeDriver e do Node
      - name: Instala as dependências
        run: |
          apt-get update && apt-get install -y wget unzip && \
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
          apt-get update && apt-get install -y google-chrome-stable && \
          wget https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip && \
          unzip chromedriver_linux64.zip && \
          mv chromedriver /usr/bin/chromedriver && \
          chmod +x /usr/bin/chromedriver && \
          curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
          apt-get install -y nodejs && \
          npm install -g npm
      
      # Executa os testes no modo headless no Google Chrome
      - name: Executa os testes no modo headless no Google Chrome
        run: |
          pip install -r E2E/requirements.txt
          robot --outputdir E2E/Results --variable BROWSER:chrome --variable HEADLESS:True E2E/Tests

      # Define a ação a ser executada mesmo que os testes falhem
      - name: Ação a ser executada mesmo que os testes falhem
        continue-on-error: true
        run: echo "Os testes falharam, mas a pipeline continua"
