on:
  push:
  pull_request:

name: Testes Web com Google Chrome na nuvem
jobs:
  testes_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Instalar dependências
      run: npm install
services:
  chrome:
    image: selenium/standalone-chrome
    options: --shm-size=2g
steps:
- name: Iniciar Selenium
  run: |
    docker pull selenium/standalone-chrome
    docker run -d -p 4444:4444 --shm-size=2g selenium/standalone-chrome
- name: Executar testes
  env:
    SELENIUM_HUB_URL: http://localhost:4444/wd/hub
  run: npm test || echo "Testes falharam"
