name: Testes Web com Robot Framework

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.9-slim-buster
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
        curl \
        unzip \
        && curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/chrome.deb \
        && dpkg -i /tmp/chrome.deb || apt-get install -yf \
        && curl https://chromedriver.storage.googleapis.com/`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip --output /tmp/chromedriver.zip \
        && unzip /tmp/chromedriver.zip -d /usr/local/bin/ \
        && npm install -g npm
    - name: Run tests
      working-directory: ./E2E
      run: |
        npm install
        robot -d results -v BROWSER:chrome tests.robot || true
